spring:
  datasource:
    master: 
      name: master
      url: jdbc:mysql://localhost:3306/test
      connectionProperties: serverTimezone=CTT;useUnicode=true;characterEncoding=utf-8;allowMultiQueries=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      username: zero
      password: 123456
      #配置初始化大小、最小、最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      #配置从连接池获取连接等待超时的时间
      maxWait: 10000
      # 配置一个连接在池中最大空闲时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      #配置间隔多久启动一次DestroyThread，对连接池内的连接才进行一次检测，单位是毫秒。
      #检测时:1.如果连接空闲并且超过minIdle以外的连接，如果空闲时间超过minEvictableIdleTimeMillis设置的值则直接物理关闭。2.在minIdle以内的不处理
      timeBetweenEvictionRunsMillis: 600000
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能 
      testOnReturn: false
      #设置从连接池获取连接时是否检查连接有效性，true时，如果连接空闲时间超过minEvictableIdleTimeMillis进行检查，否则不检查;false时，不检查
      testWhileIdle: true
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5（不含）以下建议关闭
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #检测语句
      validationQuery: SELECT 1 FROM DUAL
      filters: stat,wall,log4j
    slave: 
      name: slave
      url: jdbc:mysql://localhost:3306/test2
      connectionProperties: serverTimezone=CTT;useUnicode=true;characterEncoding=utf-8;allowMultiQueries=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      username: zero
      password: 123456
      #配置初始化大小、最小、最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      #配置从连接池获取连接等待超时的时间
      maxWait: 10000
      # 配置一个连接在池中最大空闲时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      #配置间隔多久启动一次DestroyThread，对连接池内的连接才进行一次检测，单位是毫秒。
      #检测时:1.如果连接空闲并且超过minIdle以外的连接，如果空闲时间超过minEvictableIdleTimeMillis设置的值则直接物理关闭。2.在minIdle以内的不处理
      timeBetweenEvictionRunsMillis: 600000
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能 
      testOnReturn: false
      #设置从连接池获取连接时是否检查连接有效性，true时，如果连接空闲时间超过minEvictableIdleTimeMillis进行检查，否则不检查;false时，不检查
      testWhileIdle: true
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5（不含）以下建议关闭
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #检测语句
      validationQuery: SELECT 1 FROM DUAL
      filters: stat,wall,log4j
    druid:
      #监控页面设置
      stat-view-servlet: 
        enabled: true
        loginUsername: admin
        loginPassword: admin
      web-stat-filter:
        enabled: true
 
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    